[project]
name = "mi-proyecto-speckit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luis Serpa", email = "luiserpandrade@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
convertidor-temperatura = "temperature_converter.cli:main"
mi-proyecto-speckit = "mi_proyecto_speckit:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
